name: Run Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - ready-for-test
  workflow_dispatch:
  
permissions:
  contents: read  # Allows reading repository contents
  pages: write    # Allows publishing to GitHub Pages
  id-token: write # Required for authentication

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.head_ref }} # Check out the PR branch

    - name: Build the Docker image
      run: |
        npm run docker:build

    - name: Run the Docker container
      run: |
        npm run docker:run

    - name: Wait for the app to start
      run: |
        sleep 10  # Wait for a few seconds to let the app start

    - name: Install Dependencies
      run: |
        npm install
      working-directory: ./tests

    - name: Cypress run
      uses: cypress-io/github-action@v6.6.1
      with:
        browser: chrome
        install: true
        working-directory: ./tests
        config-file: cypress.config.js

    - name: Stop the Docker container
      if: always()
      run: |
        docker ps -q | xargs docker stop

  deploy_to_pages:
    needs: cypress-tests
    uses: w4dd325/automated-pipeline/.github/workflows/deploy-from-action.yaml@main