name: GitHub Pages From Action

on:
  workflow_call:
  workflow_dispatch:
  
permissions:
  contents: read  # Allows reading repository contents
  pages: write    # Allows publishing to GitHub Pages
  id-token: write # Required for authentication
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          branch: ready-for-test

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/

      # MERGE TO READY-FOR-TEST BRANCH
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge feature into ready-for-test
        run: |
          git checkout ready-for-test
          git pull origin ready-for-test
          git merge --no-ff feature -m "Auto-merging feature into ready-for-test"
          git push origin ready-for-test

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy_to_pages:
    needs: deploy
    uses: w4dd325/automated-pipeline/.github/workflows/post-deployment-test.yaml@main
    with:
      ref: ready-for-test
