name: Ex 1 - Pretend Security Checks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      
      - name: Echo Message
        run: echo "This is a pretend security workflow..."
