name: Post Deployment Test

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  check-pages-status:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Pages Deployment Passed
        run: |
          echo "Waiting for GitHub Pages deployment to complete..."

          GITHUB_API="https://api.github.com/repos/${{ github.repository }}/actions/runs"
          STATUS=""
          ATTEMPTS=0
          MAX_ATTEMPTS=30  # 30 attempts * 10s = 5 minutes

          while [[ "$STATUS" != "completed" && $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
            STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$GITHUB_API" \
              | jq -r '.workflow_runs[] | select(.name=="pages-build-deployment") | .status' | head -n 1)

            if [[ "$STATUS" == "completed" ]]; then
              CONCLUSION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$GITHUB_API" \
                | jq -r '.workflow_runs[] | select(.name=="pages-build-deployment") | .conclusion' | head -n 1)

              if [[ "$CONCLUSION" == "success" ]]; then
                echo "GitHub Pages deployment completed successfully!"
                exit 0
              else
                echo "GitHub Pages deployment failed!"
                exit 1
              fi
            fi

            echo "Deployment still in progress... Checking again in 10 seconds."
            sleep 10
            ((ATTEMPTS++))
          done

          echo "GitHub Pages deployment did not complete within 5 minutes."
          exit 1

  run-post-deployment-tests:
    needs: check-pages-status
    runs-on: ubuntu-latest
    steps:
      - name: Run Final Tests
        run: echo "GitHub Pages deployment is complete! Running final tests."

      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          install: true
          working-directory: tests
          config-file: cypress.config.js
        env:
          CYPRESS_BASE_URL: 'https://w4dd325.github.io/automated-pipeline/'